openapi: 3.0.0
info:
  version: 0.0.1
  title: managingPromotions
  description: managingPromotionsApplications
paths:
  /health:
    get:
      description: This is healt description
      operationId: GetHealtMsg
      tags:
        - Health
      responses:
        "200":
          description: Applications is alive

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: int
        id:
          type: string
        description:
          type: string

    EmployeeDTO:
      type: object
      properties:
        employeeCode:
          type: string

    ProductDTO:
      type: object
      properties:
        productName:
          type: string
        description:
          type: string
        price:
          type: number
          format: currency
        category:
          type: string
        expiryDate:
          type: string
          format: date

    LoginCredentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    CreateIdResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64

    GroceryListProductDTO:
      type: object
      properties:
        name:
          type: string
        unit:
          type: string
        amount:
          type: int

    GroceryListRequestDTO:
      type: object
      properties:
        name:
          type: string
        userLogin:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/GroceryListProductDTO'

    GroceryListResponseDTO:
      type: object
      properties:
        name:
          type: string
        createDate:
          type: string
          format: date
        modifyDate:
          type: string
          format: date
        products:
          type: array
          items:
            $ref: '#/components/schemas/GroceryListProductDTO'

    GroceryListModifyRequestDTO:
      type: object
      properties:
        name:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/GroceryListProductDTO'

    ParsedProductDTO:
      type: object
      properties:
        name:
          type: string
        unit:
          type: string
        amount:
          type: int
        price:
          type: number

    ProductParsedFromShopDTO:
      type: object
      properties:
        shopName:
          type: string
        groceryListId:
          type: integer
          format: int64
        products:
          type: array
          items:
            $ref: '#/components/schemas/ParsedProductDTO'

    ShopEnum:
      type: string
      enum:
        - ELECLERC
        - CARREFOUR
        - AUCHAN
        - GROSZEK

    CheapestShoppingReponse:
      type: object
      properties:
        shopName:
          type: string
        groceryListId:
          type: integer
          format: int64
        price:
          type: number
          format: currency
        products:
          type: array
          items:
            $ref: '#/components/schemas/ParsedProductDTO'

    ListProductParsedFromShopDTO:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductParsedFromShopDTO'

