openapi: 3.0.0
info:
  version: 0.0.1
  title: managingPromotions
  description: managingPromotionsApplications
paths:
  /health:
    get:
      description: This is healt description
      operationId: GetHealtMsg
      tags:
        - Health
      responses:
        "200":
          description: Applications is alive

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: int
        id:
          type: string
        description:
          type: string

    EmployeeDTO:
      type: object
      properties:
        employeeCode:
          type: string

    ProductDTO:
      type: object
      properties:
        productName:
          type: string
        description:
          type: string
        price:
          type: number
          format: currency
        category:
          type: string
        expiryDate:
          type: string
          format: date

    LoginCredentials:
      required:
        - username
        - password
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    CreateIdResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64

    GroceryListProductDTO:
      type: object
      properties:
        name:
          type: string
        unit:
          type: string
        amount:
          type: number

    GroceryListRequestDTO:
      type: object
      properties:
        name:
          type: string
        userLogin:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/GroceryListProductDTO'

    GroceryListResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        createDate:
          type: string
          format: date
        modifyDate:
          type: string
          format: date
        products:
          type: array
          items:
            $ref: '#/components/schemas/GroceryListProductDTO'

    GroceryListModifyRequestDTO:
      type: object
      properties:
        name:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/GroceryListProductDTO'

    ParsedProductDTO:
      type: object
      properties:
        name:
          type: string
        unit:
          type: string
        amount:
          type: number
        price:
          type: number

    ProductParsedFromShopDTO:
      type: object
      properties:
        shopName:
          $ref: '#/components/schemas/ShopEnum'
        productFromGroceryList:
          type: string
        groceryListId:
          type: integer
          format: int64
        products:
          type: array
          items:
            $ref: '#/components/schemas/ParsedProductDTO'

    ShopEnum:
      type: string
      enum:
        - ELECLERC
        - CARREFOUR
        - AUCHAN
        - GROSZEK

    CheapestShoppingReponse:
      type: object
      properties:
        shopName:
          type: string
        groceryListId:
          type: integer
          format: int64
        price:
          type: number
          format: currency
        products:
          type: array
          items:
            $ref: '#/components/schemas/ParsedProductDTO'

    LetterNewsletterResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        shopName:
          $ref: '#/components/schemas/ShopEnum'
        fileName:
          type: string
        extension:
          type: string

    LetterNewsletterDTO:
      allOf:
        - $ref: '#/components/schemas/LetterNewsletterResponseDTO'
        - type: object
          properties:
            file:
              type: string
              format: base64

    RegistrationCredentials:
      required:
        - passwordConfirmation
      allOf:
        - $ref: '#/components/schemas/LoginCredentials'
        - type: object
          properties:
            passwordConfirmation:
              type: string

    UserAppResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
